### ISSUE TITLE
TEXTURE SPLATTING?!

### ISSUE THREAD

**Issue by Thundros** [Hashiyaa/my-graphics-island#1]
Hello, @Hashiyaa ! :) First off I'd like to say : GIVE YOURSELF A PAT ON THE BACK! THIS PROJECT IS AWESOME! Keep up the GREAT work!

Secondly, I'd like to ask if you can add Texture Splatting RGBA map to the Terrain?

Once again, PLEASE keep up the GREAT work & have a GREAT day! <3

**Comment by Hashiyaa** [comment]
Thanks for the praise! Actually I am still a newbie and trying to look more depth into THREE.js and CG stuff. It is a great idea to have texture splatting for the terrain! I will try to work it out these days. <3

**Comment by Thundros** [comment]
@Hashiyaa : You are welcome! <3 I think it would be GREAT to allow for saving of the new texture quality along w/ Terrain as well! <3

**Comment by Thundros** [comment]
@Hashiyaa : Any luck? :) HAPPY MEMORIAL DAY BTW! <3

**Comment by Thundros** [comment]
@Hashiyaa : I see that you are now using Shaders for the terrain! Can you PLEASE do texture splatting for at LEAST 4 textures using RGBA splat maps?

Here's a few examples : 

![splatmap](https://user-images.githubusercontent.com/32390102/82961754-e9302480-9f83-11ea-8773-016b1a0bfc33.png)
![splat3](https://user-images.githubusercontent.com/32390102/82961764-f0efc900-9f83-11ea-8c17-b866cd6ae452.jpg)
![splat2](https://user-images.githubusercontent.com/32390102/82961765-f0efc900-9f83-11ea-8a36-387462ac976e.png)
![splat1](https://user-images.githubusercontent.com/32390102/82961766-f1885f80-9f83-11ea-939b-0681deb7813b.png)

**Comment by Hashiyaa** [comment]
Sure, I will have a try! I transfer to shaders since I find it may be easier to do texture splatting with shaders, but there are still some issues I need to figure out in order to work with shaders. Thanks for following up on this project! (I have been procrastinating...)

**Comment by Thundros** [comment]
@Hashiyaa : You are welcome! I would be MORE than HONORED to test it for you if you like! <3

Thank you for doing this brother! <3

**Comment by Hashiyaa** [comment]
@Thundros Hi bro, I added a basic texture splatting on the terrain. I basically adapted ideas from http://stemkoski.github.io/Three.js/Shader-Heightmap-Textures.html. I am not 100% sure that it meets your expectation, but you are more than welcome to play around the code and test it. Thanks!

**Comment by Thundros** [comment]
@Hashiyaa : Hey bro! This one does not use an RGBA splatmap. At least the demo linked above doesn't. This is a bit more what I had in mind.

https://unitycoder.com/blog/2013/08/26/mesh-terrain-texturingsplatmap-tool-wip/

Does this help? :)

**Comment by Hashiyaa** [comment]
@Thundros Oh, I see what you mean. I guess that it would be really convenient to configure a terrain with RGBA splat maps and other textures then. Technically I think that it won't be very different from what I am doing now, but RGBA splat maps will be cooler for sure. I will try to get it to work.

**Comment by Thundros** [comment]
@Hashiyaa : I would be HONORED to test it for you! Please do let me know! <3

**Comment by Hashiyaa** [comment]
@Thundros Hi bro, I tried to combine a rgba splatmap with my original heightmap. Can you confirm that I go in the right direction? The code is a little messy currently, but I will try to clean it up later. You are more than welcome to play around the code btw.

**Comment by Thundros** [comment]
@Hashiyaa : Absolutely, brother! I am more than HONORED to beta test it for you! <3

**Comment by Thundros** [comment]
@Hashiyaa : GREAT job! It seems to almost work. What we need is the ability to change the quality of each of the textures splatted on to the map, the ability to have more than 4 textures & the ability to save the terrain with the new textures at the new quality of each of the textures splatted on to the map. Also, I noticed the textures stretches the higher up a mountain becomes.

**Comment by Hashiyaa** [comment]
@Thundros I am not sure how to do these things for now, but I am glad to have a try since it sounds interesting! The original intention of this project was to build a graphics island with shaders, models, and etc, but it looks like a good idea to implement a terrain editor instead lol. Is your project available on Github? Maybe you can give me a pointer to your project so that I may have a better idea of what is going on?

**Comment by Thundros** [comment]
@Hashiyaa : These are 2 examples of what I mean :  https://tech.innogames.com/terrain-shader-in-unity/ https://api.unity.com/v1/oauth2/authorize?client_id=unity_forum&response_type=code&redirect_uri=https%3A%2F%2Fforum.unity.com%2Fregister%2Fgenesis&state=OTilODLJG69iDxtpMme5il3SlhHoIsqUj7Goz9Up%3B%2Fthreads%2Freleased-megasplat-a-256-texture-splat-mapping-system.441329%2F&prompt=NONE

**Comment by Thundros** [comment]
Hey, @Hashiyaa ! How is it going? <3

**Comment by Thundros** [comment]
@Hashiyaa : Hello, brother! How is the project progressing?

**Comment by Thundros** [comment]
@Hashiyaa Wonderful! <3

**Comment by Thundros** [comment]
@Hashiyaa : Hey brother! Let me know when you work on it this weekend & I will be MORE than happy to test it! <3 Thank You! <3

**Comment by Hashiyaa** [comment]
@Thundros Hi, I see that you created a repo named rgba-splatmap with basically all my code in it. Maybe you are trying to test my code in this way, but you have better ways to do that, such as testing the code in your local copy of my project. I'm not sure why you need this project, but I didn't find proper attributions in your repo. My repo doesn't have a license, so technically it's inappropriate to copy the code. Please refer to [(https://choosealicense.com/no-permission/](url) for this point. I don't know if it's legal for you to do that, but I am unhappy with it.

**Comment by Thundros** [comment]
@Hashiyaa my apologies, i was testing it. I can remove it if you like.

**Comment by Thundros** [comment]
@Hashiyaa : I have removed it. My apologies.

**Comment by Thundros** [comment]
Also, please show me the attributions file, and I will add it.

**Comment by Hashiyaa** [comment]
@Thundros That's fine. If you mean the license for "attribution files", I don't plan to add a license to my repo for now since it is only a simple demo. Another thing is that I have no obligation to maintain my project, and I will do it when I want to. You can start your own repo on rgba splat map and adapt ideas from my project as long as it is not simply copying my code and you give proper attributions in your README. Or you can work on my project by making pull requests. If you don't have any problems with this, I'm gonna close this issue.

**Comment by Thundros** [comment]
@Hashiyaa Sounds good to me! :)
